# Generated by Django 4.1.3 on 2022-11-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YieldRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', help_text='Yield of this year in 1000s of megatons', max_length=20)),
                ('yield_value', models.CharField(default='', help_text='Yield Value in 1000s of megatons', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation date and time')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Record creation date and time')),
            ],
            options={
                'verbose_name': 'YieldRecords',
                'verbose_name_plural': 'YieldRecords',
            },
        ),
        migrations.CreateModel(
            name='WeatherRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(default='', help_text='Used file name as weather station', max_length=30)),
                ('date', models.DateField(default='', help_text='Date of this weather record')),
                ('maximum_temperature', models.CharField(default='', help_text='The maximum temperature for that day (in tenths of a degree Celsius)', max_length=20)),
                ('minimum_temperature', models.CharField(default='', help_text='The minimum temperature for that day (in tenths of a degree Celsius)', max_length=20)),
                ('amount_of_precipitation', models.CharField(default='', help_text='The amount of precipitation for that day (in tenths of a millimeter)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation date and time')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Record creation date and time')),
            ],
            options={
                'verbose_name': 'WeatherRecords',
                'verbose_name_plural': 'WeatherRecords',
                'unique_together': {('station_id', 'date')},
            },
        ),
    ]
