# Generated by Django 4.1.3 on 2022-11-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(default='', help_text='Statistics of weather station', max_length=30)),
                ('statistics', models.TextField(default='', help_text='statistics year wise')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation date and time')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Record creation date and time')),
            ],
            options={
                'verbose_name': 'StatRecords',
                'verbose_name_plural': 'StatRecords',
            },
        ),
    ]
