# Generated by Django 4.1.3 on 2022-11-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_statrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statrecords',
            name='station_id',
            field=models.CharField(default='', help_text='Statistics of weather station', max_length=30, unique=True),
        ),
    ]
